# Generated by Django 5.0.3 on 2024-04-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comments_bids_listing_bid_listing_bidder_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.BooleanField(default='True'),
        ),
    ]
