# Generated by Django 5.0.3 on 2024-04-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.ManyToManyField(blank=True, null=True, related_name='offer', to='auctions.bids'),
        ),
    ]
