# Generated by Django 5.0.3 on 2024-05-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_winner_alter_bids_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bidder_comments',
        ),
        migrations.AddField(
            model_name='listing',
            name='bidder_comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='review', to='auctions.comments'),
        ),
    ]
