# Generated by Django 5.0.3 on 2024-05-17 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listing_bidder_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bidder_comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='auctions.listing'),
        ),
    ]
