# Generated by Django 5.0.3 on 2024-06-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
